### ISSUE TITLE
Add arena ranks (heroes & ships)

### ISSUE THREAD

**Issue by ALton450** [PopGoesTheWza/swgoh-sheets-core#1]
In the coreRoster sheets, having the ship and characters arena rank would be very useful

**Comment by PopGoesTheWza** [comment]
arena & fleet can be easily requested from SwgohHelp api. On SwgohGg api, only "arena_rank" seems available at the moment.

**Comment by PopGoesTheWza** [comment]
Code for arena ranks added to the code base. Pending tests (and SwgohGg support for fleet arena rank)
